[package]
name = "riddle"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
pest = "2.8.5"
pest_derive = "2.8.5"
cranelift = "0.116.1"
cranelift-module = "0.116.1"
cranelift-jit = "0.116.1"
cranelift-frontend = "0.116.1"
target-lexicon = "0.12"