[package]
name = "riddle"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[[bin]]
name = "riddle"
path = "src/main.rs"

[dependencies]
pest = "2.8.5"
pest_derive = "2.8.5"
cranelift = "0.128.3"
cranelift-module = "0.128.3"
cranelift-object = "0.128.3"
cranelift-native = "0.128.3"